Controllers/ComplaintController.cs
using ComplaintTracker.DAL;
using ComplaintTracker.ExternalAPI;
using ComplaintTracker.Handler;
using ComplaintTracker.Models;
using Serilog;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Xml.Linq;
using static ComplaintTracker.JqueryDatatableParam;
using static System.Net.WebRequestMethods;
using Microsoft.Office.Interop.Excel;


namespace ComplaintTracker.Controllers
{
    [Authorize]
    public class ComplaintController : Controller
    {
        // GET: Complaint
        static readonly Serilog.ILogger log = EventLogger._log;
        public ActionResult Index()
        {
            COMPLAINT objComplaint = new COMPLAINT();
            ViewBag.fromDate = Convert.ToDateTime("1900-01-01");
            ViewBag.toDate = Convert.ToDateTime("1900-01-01");
            ViewBag.RoleID = Session["Roll_ID"];
            //objComplaint.ComplaintTypeCollection = Repository.GetComplaintTypeList("0");
            return View(objComplaint);
        }

        // GET: Complaint/Create
        public ActionResult Create()
        {
            COMPLAINT obj = new COMPLAINT();
            ViewBag.fromDate = DateTime.Now;
            ViewBag.toDate = DateTime.Now.AddDays(1);
            obj.OfficeCodeCollection = Repository.GetOfficeList_Create(Session["UserID"].ToString());
            return View(obj);
        }

        // POST: Complaint/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(COMPLAINT modelComplaint)
        {
            COMPLAINT obj = new COMPLAINT();
            obj.OfficeCodeCollection = Repository.GetOfficeList(Session["OFFICE_ID"].ToString());

            if (modelComplaint.OFFICE_CODE_ID == 0 || string.IsNullOrEmpty(modelComplaint.JE_AREA))
            {
                return View(obj);
            }

            try
            {
                string complaintNo = await Repository.SaveComplaint(modelComplaint);
                if (complaintNo != "0")
                {
                    
                    TempData["AlertMessage"] = "Complaint No. " + complaintNo.ToString() + " Generated Successfully...!";
                    return RedirectToAction("Create", obj);
                }
                else
                {
                    TempData["AlertMessage"] = "Error in complaint Generating...!";
                    return View(obj);
                }
             
            }
            catch
            {
                return View(obj);
            }
        }


        [HttpGet]
        public ActionResult EditComplaint(Int64 ComplaintNo)
        {
            COMPLAINT cOMPLAINT = new COMPLAINT();
            cOMPLAINT = Repository.GetMobileEmail(ComplaintNo);

            return PartialView("_editComplaint", cOMPLAINT);
        }

        [HttpPost]
        public async Task<ActionResult> EditComplaint(COMPLAINT modelComplaint)
        {
            COMPLAINT cOMPLAINT = new COMPLAINT();
            Int64 complaintNo = await Repository.EditComplaint(modelComplaint);
            TempData["AlertMessage"] = "Information of Complaint No. " + modelComplaint.COMPLAINT_NO.ToString() + " Saved Successfully...!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GetOfficeListByParentOffice(int parentOfficeId)
        {
            List<ModelOfficeCode> lstOfficeCode = new List<ModelOfficeCode>();
            ModelOfficeCode objBlank = new ModelOfficeCode();
            //objBlank.OfficeId = "0";
            //objBlank.OfficeCode = "Select JEn Area";
            //lstOfficeCode.Insert(0, objBlank);

            SqlParameter[] param ={
                    new SqlParameter("@Parent_OfficeId",parentOfficeId) };
            DataSet ds = SqlHelper.ExecuteDataset(HelperClass.Connection, CommandType.StoredProcedure, "GetOfficeByParent", param);

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                objBlank = new ModelOfficeCode();
                objBlank.OfficeCode = dr.ItemArray[0].ToString();
                objBlank.OfficeId = dr.ItemArray[1].ToString();
                lstOfficeCode.Add(objBlank);
            }
            return Json(lstOfficeCode, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetFRTNo(int parentOfficeId)
        {
            List<ModelOfficeCode> lstOfficeCode = new List<ModelOfficeCode>();
            ModelOfficeCode objBlank = new ModelOfficeCode();
            //objBlank.OfficeId = "0";
            //objBlank.OfficeCode = "Select JEn Area";
            //lstOfficeCode.Insert(0, objBlank);

            SqlParameter[] param ={
                    new SqlParameter("@OFFICE_ID",parentOfficeId) };
            DataSet ds = SqlHelper.ExecuteDataset(HelperClass.Connection, CommandType.StoredProcedure, "FRT_CONTACT_DETAIL", param);

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                objBlank = new ModelOfficeCode();
                objBlank.OfficeCode = dr.ItemArray[0].ToString();
                objBlank.OfficeId = dr.ItemArray[1].ToString();
                lstOfficeCode.Add(objBlank);
            }
            return Json(lstOfficeCode, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetSubComplaintByComplaintTypeId(int ComplaintTypeId)
        {
            List<ModelComplaintType> lstSubComplaintType = new List<ModelComplaintType>();

            lstSubComplaintType = Repository.GetSubComplaintTypeList(ComplaintTypeId);


            return Json(lstSubComplaintType, JsonRequestBehavior.AllowGet);
        }
        //public JsonResult GetList(int OfficeCode, int ConsumerType, string Searchtype, string Searchparm)
        //{
        //    List<COMPLAINT> data = new List<COMPLAINT>();

        //    data = Repository.GetPreviousComplaint(OfficeCode, ConsumerType, Searchtype, Searchparm);
        //    return Json(data, JsonRequestBehavior.AllowGet);

        //}

        public JsonResult GetList(int OfficeCode, int ConsumerType, string Searchparm)
        {
            List<COMPLAINT> data = new List<COMPLAINT>();
            data = Repository.GetPreviousComplaint(OfficeCode, ConsumerType, Searchparm);
            return Json(data, JsonRequestBehavior.AllowGet);

        }


        public JsonResult ComplaintTypeJson() //It will be fired from Jquery ajax call
        {
            List<ModelComplaintType> data = new List<ModelComplaintType>();
            data = Repository.GetComplaintTypeList("0");
            var jsonData = data;
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult OfficeCodeJson() //It will be fired from Jquery ajax call
        {
            List<ModelOfficeCode> data = new List<ModelOfficeCode>();
            data = Repository.GetOfficeList(Session["OFFICE_ID"].ToString());
            var jsonData = data;
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        public JsonResult OfficeCodeJsonCircle() //It will be fired from Jquery ajax call
        {
            List<ModelOfficeCode> data = new List<ModelOfficeCode>();
            data = Repository.GetOfficeListCircle(Session["OFFICE_ID"].ToString());
            var jsonData = data;
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ComplaintSourceJson() //It will be fired from Jquery ajax call
        {
            List<SelectListItem> data = new List<SelectListItem>();
            data = Repository.ComplaintSourceJson();
            //data.Insert(0, new SelectListItem());   
            var jsonData = data;
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GetComplaintSearch(DataTableAjaxPostModel model) //It will be fired from Jquery ajax call
        {
            ModelSearchComplaint dataObject = new ModelSearchComplaint();
            List<ModelSearchComplaint> data = new List<ModelSearchComplaint>();
            if (ModelState.IsValid)
            {
                try
                {
                    dataObject.UserID = Convert.ToInt64(Session["UserID"].ToString());
                    dataObject.draw = model.draw;
                    dataObject.start = model.start;
                    dataObject.length = model.length;
                    data = Repository.GetComplaintDetails(dataObject);
                    int count = data.Count() > 0 ? data[0].Total : 0;
                    return Json(new { draw = dataObject.draw, recordsFiltered = count, recordsTotal = count, data = data }, JsonRequestBehavior.AllowGet);

                }
                catch
                {
                    return Json(new { draw = dataObject.draw, recordsFiltered = 0, recordsTotal = 0, data = data }, JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }

        //[HttpPost]
        //public ActionResult ExportToExcelRawComplaint(string searchComplaintno, string searchKno, string searchaccountno, string searchmobileno, string ddlOfficecode, string ddlSource, string ddlstatus, string ddlassigned, string fromdate, string todate, string ComplaintTypeId)
        //{

        //    List<ModelSearchComplaint> lstdata = new List<ModelSearchComplaint>();
        //    ModelSearchComplaint dataObject = new ModelSearchComplaint();
        //    COMPLAINT objComplaint = new COMPLAINT();

        //    dataObject.draw = 0;
        //    dataObject.start = 0;

Views/Complaint/_CallTransfer.cshtml
@*Remark Model*@
@model List<SelectList>



@using (Html.BeginForm("CallTransfer", "Complaint", FormMethod.Post))
{

    <div class="modal fade" id="remarkPopup" tabindex="-1" aria-hidden="true" style="display: none;" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header with-border bg-primary text-white">
                    <h2 class="modal-title"> Call Transfer</h2>
                    <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"><span>&times;</span> </button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3">
                        <div class="col-md-12">

                            <label for="COMPLAINT_NO">Select User</label>                            
                            @Html.DropDownList("userlist", (IEnumerable<SelectListItem>)ViewBag.lst, "[Select user]", new { @class = "form-control" })
                        </div>
                    </div>                   

                </div>
                <div class="modal-footer with-border">
                    <button type="button" class="btn btn-success" onclick="callKno(userlist.value)"><i class="align-middle me-2 fas fa-fw fa-phone"></i></button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    var callKno = function (uid) {
    alert(phone_number);
             var PostBackURL = '@System.Configuration.ConfigurationManager.AppSettings["ExternalApiURL"]';
            var user='@System.Configuration.ConfigurationManager.AppSettings["APIUser"]';
            var pass='@System.Configuration.ConfigurationManager.AppSettings["APIPassword"]';

            $.ajax({
                type: "GET",
                crossDomain: true,
                url: PostBackURL,
                contentType: "application/text; charset=utf-8",
                data: { "user": user, "pass": pass, "agent_user": uid, "function": "agent_transfer", "phone_number": phone_number, "phone_code": "91" },
                datatype: "json",
                success: function (response) {
                    alert(response);
                },
                error: function (xhr, status) {
                    alert(status);
                }
            });

    }
    var hangup = function () {
        var PostBackURL = '@System.Configuration.ConfigurationManager.AppSettings["ExternalApiURL"]';
            var user='@System.Configuration.ConfigurationManager.AppSettings["APIUser"]';
            var pass='@System.Configuration.ConfigurationManager.AppSettings["APIPassword"]';

        $.ajax({
            type: "GET",
            crossDomain: true,
            url: PostBackURL,
            contentType: "application/text; charset=utf-8",
            data: { "user": user, "pass": pass, "agent_user": uid, "function": "external_hangup" },
            datatype: "json",
            success: function (response) {
                alert(response);
            },
            error: function (xhr, status) {
                alert(status);
            }
        });

    }
</script>

Views/Complaint/_Close.cshtml
@*Close Model*@



<script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@{
    var toDate = (DateTime)ViewBag.toDate;
}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        $('#toDate1').datetimepicker();
   });

    $(document).ready(function () {
        $('#toDate1').datetimepicker();
        $(function () {

                $('select').select2({
                    dropdownCssClass: 'custom-dropdown'
                });
                $('select').on('select2:open', function (e) {
                    $('.custom-dropdown').parent().css('z-index', 99999);
                });

                $('#ddlOutage1').select2({
                    placeholder: "Outage Type",
                    minimumResultsForSearch: -1,
                    selectOnClose: true,
                    width: '370px',
                 });


            });


            $('#submitComplaint').click(function () {
                $("#UserId").val(@Session["UserId"]);
                $("#TO_DATE").val($('#toDate').val());
            });


    });
    function closeComplaint() {
        //var TeamDetailPostBackURL = '/HRPDSS/Complaint/closeComplaint';
        var newUrl= '@Url.Action("Index","Complaint")';
        var TeamDetailPostBackURL = '/Complaint/closeComplaint';
        var model = new Object();
        model.ComplaintNo = $("#ComplaintNo").val();
        model.TO_DATE = $('#toDate').val();
        model.OutageTypeCollectionId1 = $("#ddlOutage1").val();
        $.ajax({
            type: "GET",
            url: TeamDetailPostBackURL,
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            data: model,
            success: function (data) {
                if (data.status == -1) {
                    $("#ClosePopup").modal('hide');
                    window.location.href = newUrl;
                    //swal("error in saving", "error");
                }
                else {
                    $("#ClosePopup").modal('hide');
                    window.location.href = newUrl;
                    //swal("Saved Successfully", "success");
                }
            },
            error: function (data) {
                $("#ClosePopup").modal('hide');
                swal("Dynamic content load failed.!", "error");
            }
        });
    }


</script>

@model ComplaintTracker.Models.ModelCloseComplaint

@Html.HiddenFor(model => model.TO_DATE);

<div class="modal fade" id="ClosePopup" tabindex="-1" aria-hidden="true" style="display: none;" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header with-border bg-danger text-white">
                <h2 class="modal-title">Complaint Close</h2>
                <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"><span>&times;</span> </button>
            </div>
            <div class="modal-body">
                <div class="row mb-1">
                    <div class="col-md-4">
                        <label for="ComplaintNo">Complaint No.</label>
                        @Html.EditorFor(model => model.ComplaintNo, new { htmlAttributes = new { placeholder = "Complaint No.", @class = "form-control", @disabled = "disabled" } })

                        @Html.HiddenFor(model => model.ComplaintNo)

                    </div>
                    <div class="col-md-4">
                        <label for="toDate1">Resolved Date</label>
                        @*<div class="input-group date" id="toDate1" data-target-input="nearest">

            <input type="text" class="form-control datetimepicker-input" data-target="#toDate1" id="toDate" />


            <div class="input-group-text" data-target="#toDate1" data-toggle="datetimepicker">
                <i class="fa fa-calendar"></i>
            </div>
        </div>*@
                        <div class="input-group date" id="toDate1" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" data-target="#toDate1" id="toDate" value="@toDate" />
                            <div class="input-group-text" data-target="#toDate1" data-toggle="datetimepicker">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="OutageTypeCollectionId1">Complaint Category</label>
                        @Html.DropDownListFor(x => Model.OutageTypeCollectionId1, new SelectList(Model.OutageTypeCollection1, "Value", "Text"), new { @class = "form-control", id = "ddlOutage1" })

                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="submitComplaint" onclick="closeComplaint()">Update</button>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Close</button>
            </div>
        </div>
    </div>
</div>

Views/Complaint/_ConsumerContactSelection.cshtml
@*Remark Model*@
@model  IList<ComplaintTracker.Models.COMPLAINT>

@using (Html.BeginForm("PartialComplaintDetails", "Complaint", FormMethod.Get))
{
    <div class="modal fade" id="consumerComplaintListPopup" tabindex="-1" aria-hidden="true" style="display: none;" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header with-border bg-primary  text-white">
                    <h2 class="modal-title"> Complaint Details</h2>
                    <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"><span>&times;</span> </button>
                </div>
                <div class="modal-body">


                    <table id="gridComplaintlog" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address1</th>
                                <th>Address2</th>
                                <th>Address3</th>
                                <th>Mobile No.</th>
                                <th>KNO</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody class="tbody">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.NAME</td>
                                    <td>@item.ADDRESS1</td>
                                    <td>@item.ADDRESS2</td>
                                    <td>@item.ADDRESS3</td>
                                    <td>@item.MOBILE_NO</td>
                                    <td>@item.KNO</td>
                                    <td><button type="button" onclick="getDetailsofKo(@item.KNO)" class="btn btn-primary btnget tooltip-test" aria-label="select"  title="kno selection for complaint">Select</button></td>
                                    @*onclick="getDetailsofKo()"*@
                                </tr>
                            }
                            </tbody>
                    </table>

                </div>
                <div class="modal-footer with-border">
                    @*<button type="button" class="btn btn-success" id="btnUpdate">Update</button>*@
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close" id="btnclose">Close</button>
                </div>
            </div>

        </div>
    </div>
}


<script>
    
        //$(document).on("click", "#gridComplaintlog button.btnget", function () {
        //    var kno = $(this).closest('tr').children('td:eq(5)').text();
        //    alert();
        //    getDetailsofKo(kno)

        // });
    

    //$("#gridComplaintlog").click(function () {
    //    var kno = $(this).find('td:eq(5)').text();
    //    getDetailsofKo(kno);
    //});

    function getDetailsofKo(kno) {
        var officecode = '0';
        var consumerType = '1';
        var searchparm = kno ;


         $.ajax({
                type: "GET",
                url: '/Complaint/GetList',
                data: { OfficeCode: officecode, ConsumerType: consumerType, Searchparm: searchparm },
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                async: "true",
                cache: "false",
                success: function (data) {
                    $('#comp').DataTable(
                        {
                            data: data,
                            columns: [
                                { 'data': 'Complaintdate' },
                                { 'data': 'COMPLAINT_NO' },
                                { 'data': 'COMPLAINT_TYPE' },
                                { 'data': 'REMARKS' },
                                { 'data': 'COMPLAINT_status' },
                            ],
                            //lengthMenu: [[10, 15, 20, 50, 100, -1], [10, 15, 20, 50, 100, "All"]],
                            //bPaginate: true,
                            processing: true,
                            pageLength: 5,
                            lengthChange: false,
                            bFilter: false,
                            destroy: true,
                            bSort: false
                        });
                    $('#comp').DataTable().row("tr:first-child").remove().draw();

                    var flag = false;
                    var nos;
                    var serviceEnable = false;
                    $.each(data, function (key, item) {
                        if (item.COMPLAINT_status == "Pending") {
                            flag = true;
                            nos = item.COMPLAINT_NO;
                        }
                        if (key == 0) {
                            if (item.CONSUMER_STATUS == 'R' || item.CONSUMER_STATUS == 'N' || item.CONSUMER_STATUS == 'F') {
                                serviceEnable = true;
                            }
                            $('#SDO_CODE').val(item.SDO_CODE);
                            $('#ADDRESS1').val(item.ADDRESS1);
                            $('#ADDRESS2').val(item.ADDRESS2);
                            $('#ADDRESS3').val(item.ADDRESS3);
                            $('#NAME').val(item.NAME);
                            $('#FATHER_NAME').val(item.FATHER_NAME);
                            $('#KNO').val(item.KNO);
                            $('#LANDMARK').val(item.LANDMARK);
                            $('#LANDLINE_NO').val(item.LANDLINE_NO);
                            $('#MOBILE_NO').val(item.MOBILE_NO);
                            $('#ALTERNATE_MOBILE_NO').val(item.ALTERNATE_MOBILE_NO);
                            $('#CONSUMER_STATUS').val(item.CONSUMER_STATUS);
                            $('#EMAIL').val(item.EMAIL);
                            $('#FEEDER_NAME').val(item.FEEDER_NAME);
                            $('#ACCOUNT_NO').val(item.ACCOUNT_NO);
                            $('#AREA_CODE').val(item.AREA_CODE);

                            $("#ddlOfficecode > option").each(function () {
                                let result = this.value.slice(0, 7);
                                if (result == item.KNO.slice(0, 7)) {
                                    $("#ddlOfficecode").val(this.value).trigger('change');   
                                }
                            });
                        }
                    });

                    if (flag == true) {
                        Swal.fire({
                            icon: 'info',
                            title: 'info',
                            text: 'Complaint Already Registered With no. ' + nos,
                            footer: 'Sandha & Co.'
                        })
                    }
                    if (serviceEnable == false && consumerType == 1) {
                        $('#submitComplaint').prop('disabled', true);
                        Swal.fire({
                            icon: 'info',
                            title: 'info',
                            text: 'Consumer is Disconnected or No Consumer Exist',
                            footer: 'Sandha & Co.'
                        })
                    } else {
                        $('#submitComplaint').prop('disabled', false);
                    }
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }

            });


        $('#btnclose').trigger('click') 
    };

</script>

Views/Complaint/_editComplaint.cshtml
@*Remark Model*@
@model ComplaintTracker.Models.COMPLAINT



@using (Html.BeginForm("EditComplaint", "Complaint", FormMethod.Post))
{
    @Html.HiddenFor(model => model.COMPLAINT_NO)
    <div class="modal fade" id="modeleditComplaint" tabindex="-1" role="dialog" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header ">
                    <h5 class="modal-title">Modify Consumer basic Information</h5>
                    <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"><span>&times;</span> </button>
                </div>
                <div class="modal-body m-3">
                    <div class="row mb-3">
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.COMPLAINT_NO, new { htmlAttributes = new { @class = "form-control", @placeholder = "Complaint No.", @disabled = "disabled" } })
                        </div>
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.KNO, new { htmlAttributes = new { @class = "form-control", @placeholder = "K No." } })
                        </div>
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                        </div>
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.FATHER_NAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Father's Name" } })
                        </div>
                        
                    </div>
                    <div class="row mb-3">
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.ADDRESS1, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address 1" } })
                        </div>
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.ADDRESS2, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address 2" } })
                        </div>
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.ADDRESS3, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address 3" } })
                        </div>
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.LANDMARK, new { htmlAttributes = new { @class = "form-control", @placeholder = "Landmark" } })
                        </div>
                        
                    </div>
                    <div class="row mb-3">
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.LANDLINE_NO, new { htmlAttributes = new { @class = "form-control", @placeholder = "Landline No." } })
                        </div>
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.MOBILE_NO, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mobile No.", type = "number", @required = "true" } })
                        </div>
                        <div class="col-12 col-lg-3">
                            @Html.EditorFor(model => model.ALTERNATE_MOBILE_NO, new { htmlAttributes = new { @class = "form-control", @placeholder = "Alternate Mobile No.", type = "number", @required = "true" } })
                        </div>
                        <div class="col-12 col-lg-3 error-placeholder">
                            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-MailID/Social Media" } })
                        </div>

                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" id="btnUpdate">Update</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Close</button>
                </div>
            </div>
        </div>
    </div>

}