Controllers/EsclatedComplaintsController.cs
using ComplaintTracker.DAL;
using ComplaintTracker.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.Xml;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Xml.Linq;

namespace ComplaintTracker.Controllers
{
    public class EsclatedComplaintsController : Controller
    {
        
        public ActionResult EsclatedComplaints()
        {
            if (Session["UserID"] != null)
            {
                ViewBag.RoleID = Session["Roll_ID"];
                List<ModelOfficeCode> objComp = new List<ModelOfficeCode>();

                objComp = Repository.GetOfficeList(Session["OFFICE_ID"].ToString());

                List<ModelComplaintType> obj = new List<ModelComplaintType>();
                obj = Repository.GetComplaintTypeList("0");
                obj[0].lstComplaint = objComp;
                if (obj.Count > 0)
                {
                    ViewBag.Title = "AVVNL Dashboard";
                }
                return View(obj);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        public JsonResult GetComplaintTypeDetails(int OfficeCode, int ComplainttypeId, int SLAType)
        {
            if (OfficeCode == 0)
            {
                OfficeCode = Convert.ToInt32(Session["OFFICE_ID"].ToString());
            }
            List<ModelEsclatedCOmplaints> data = new List<ModelEsclatedCOmplaints>();
            data = Repository.GetExclatedComplaintSummary(OfficeCode, ComplainttypeId, SLAType);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ShowEsclatedComplaint(string OfficeId, string complaintStatus,string ComplainttypeId) //It will be fired from Jquery ajax call
        {
            Int64 officeSession= Convert.ToInt64(Session["OFFICE_ID"].ToString());
            Int64 officeIdClick = Convert.ToInt64(OfficeId);
            if(officeIdClick< officeSession)
            {
                OfficeId= Session["OFFICE_ID"].ToString();
            }
            List <COMPLAINT> lstComplaints = new List<COMPLAINT>();
            lstComplaints = Repository.ShowEsclatedComplaint(OfficeId, complaintStatus, ComplainttypeId);
            return PartialView("_EsclatedComplaint", lstComplaints);
        }
        [HttpGet]
        public ActionResult ExportToExcel(string OfficeId, string complaintStatus, string ComplainttypeId)
        {
            List<COMPLAINT> lstComplaints = new List<COMPLAINT>();
            lstComplaints= Repository.ShowEsclatedComplaint(OfficeId, complaintStatus, ComplainttypeId);
            List<EsclationComplaintExcel> list = lstComplaints.AsEnumerable()
                                      .Select(o => new EsclationComplaintExcel
                                      {
                                          OfficeName = o.OfficeName,
                                          COMPLAINT_NO = o.COMPLAINT_NO,
                                          KNO=o.KNO,
                                          NAME=o.NAME,
                                          MOBILE_NO=o.MOBILE_NO,
                                          ALTERNATE_MOBILE_NO = o.ALTERNATE_MOBILE_NO   ,
                                          Complaintdate = o.Complaintdate,
                                          ComplaintTypeName = o.ComplaintTypeName,
                                          ComplaintSource = o.ComplaintSource ,
                                          ASSIGNEEName=o.ASSIGNEEName,
                                          Esclated_BY = o.Esclated_BY,
                                          Esclation_time = o.Esclation_time,

                                      }).ToList();

            var gv = new GridView();
            gv.DataSource = list;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=EsclationComplaintStatus.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }
    }
}

Views/EsclatedComplaints/EsclatedComplaints.cshtml
@model List<ComplaintTracker.Models.ModelComplaintType>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="header">
    <h1 class="header-title">
        Escalated Complaints
    </h1>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Dashboard/Index">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Escalated Complaints</li>
        </ol>
    </nav>
    <div class="row mb-3">
        <div class="col-12 col-lg-2">
            <input class="form-check-input" type="radio" name="SearchType" id="SearchType" value="1"> <font color="white"> Circle Wise</font>
        </div>
        <div class="col-12 col-lg-2">
            <input class="form-check-input" type="radio" name="SearchType" id="SearchType1" value="2"> <font color="white"> XEN Wise</font>
        </div>
        <div class="col-12 col-lg-2">
            <input class="form-check-input" type="radio" name="SearchType" id="SearchType2" value="3" checked="checked"> <font color="white"> SDO Code Wise</font>
        </div>
        <div style="width:300px;">
            @Html.DropDownListFor(x => Model[0].lstComplaint[0].OfficeId, new SelectList(Model[0].lstComplaint, "OfficeId", "OfficeCode"), new { @class = "form-control", id = "ddlOfficecode" })
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xl-12 col-xxl-12 d-flex">
        <div class="w-100">
            <div class="row">
                @foreach (var item in Model)
                {

                    <div class="col-sm-2 align-items-center">

                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col mt-0">
                                        <h5 class="card-title">@item.ComplaintType</h5>
                                    </div>
                                    <a class="small text-white stretched-link" onclick="myfun($('#@item.ComplaintTypeId').text())" href="#"></a>
                                </div>
                                <label id="@item.ComplaintTypeId" hidden>@item.ComplaintTypeId </label>
                                @*<h1 class="display-3 mt-1 mb-3">@item.COMPLAINT_COUNT</h1>*@
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>



<!--Grid-->
<div class="row">
    <div class="col-12 col-lg-12 col-xxl-12 d-flex">
        <div class="card flex-fill">
            <div class="card-header">
                <div class="card-actions float-end">
                    <a href="#" class="me-1">
                        <i class="align-middle" data-feather="refresh-cw"></i>
                    </a>
                </div>
                <h5 class="card-title mb-0">Complaint Status</h5>
            </div>
            <table id="comp" class="table table-sm">
                <thead>
                    <tr>
                        <th>SDO Name</th>
                        <th>Total Complaint Open</th>
                        <th>With In SLA</th>
                        <th>OUT Of SLA</th>
                        <th>AEN</th>
                        <th>XEN</th>
                        <th>SE</th>
                        <th>CE</th>
                        <th>Corporate</th>
                        @*<th>ComplaintType</th>*@
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<div id="loadRemarkPopUp">

</div>

<script type="text/javascript">

    minimumInputLength: 2,
    $(document).ready(() => {
        $('#ddlOfficecode').select2({
            selectOnClose: true,
            //minimumInputLength: 2,
            //maximumInputLength: 20,
            //minimumResultsForSearch: 50,
            placeholder: "Select Office Code",
        });
        //alert(@ViewBag.RoleID);
        var id=@ViewBag.RoleID;
        if (id == 5) {
            $('#SearchType').attr("disabled", true);
            $('#SearchType1').attr("disabled", true);
        }
        if (id == 6) {
            $('#SearchType').attr("disabled", true);
        }
    });

    function myfun(id) {
        $('.tbody').html('');
        var Id = $.trim(id);
        var SLATypeID;
        var officecode = $("#ddlOfficecode").val();
        if ($('#SearchType').prop('checked')) {
            SLATypeID = 1;
        } else if ($('#SearchType1').prop('checked')) {
            SLATypeID = 2;
        } else if ($('#SearchType2').prop('checked')) {
            SLATypeID = 3;
        }

        $.ajax({
            type: "GET",
            url: '/EsclatedComplaints/GetComplaintTypeDetails',
            data: { OfficeCode: officecode, ComplainttypeId: Id, SLAType: SLATypeID },
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            async: "true",
            cache: "false",
            success: function (data) {
                $('#comp').DataTable(
                    {
                        data: data,

                        columns: [
                            {
                                render: function (data, type, row, meta) {
                                    return  row.SDOName
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(1,' + row.OFFICE_CODE + ',' + id + ')">' + row.TotalComplaintOpen +'</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(2,' + row.OFFICE_CODE + ',' + id + ')">' + row.WithInSLA + '</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(3,' + row.OFFICE_CODE + ',' + id + ')">' + row.OUTOfSLA + '</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(4,' + row.OFFICE_CODE + ',' + id + ')">' + row.AEN + '</a>'
                                }
                            }, {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(5,' + row.OFFICE_CODE + ',' + id + ')">' + row.XEN + '</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(6,' + row.OFFICE_CODE + ',' + id + ')">' + row.SE + '</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(7,' + row.OFFICE_CODE + ',' + id + ')">' + row.CORPORATE + '</a>'
                                }
                            },
                            {
                                render: function (data, type, row, meta) {
                                    return '<a class=" d-inline-block fw-normal pe-auto" href="#" onclick="complaintShow(8,' + row.OFFICE_CODE + ',' + id + ')">' + row.DT + '</a>'
                                }
                            },
                            //{
                            //    render: function (data, type, row, meta) {
                            //        return id
                            //    }
                            //},
                        ],
                        processing: true,
                        pageLength: 150,
                        lengthChange: false,
                        bFilter: false,
                        createdRow: function (row, data, dataIndex) {
                            if (data['backcolor'] == 1) {

                                $(row).css('background-color', '#F0F0F0');
                            }
                            else if (data['backcolor'] == 2) {
                                $(row).css('background-color', '#D8D8D8');
                            }
                            else if (data['backcolor'] == 3) {
                                $(row).css('background-color', '#D0D0D0');
                            }
                            else if (data['backcolor'] == 4) {
                                $(row).css('background-color', '#C0C0C0');
                            }
                            else {
                                $(row).css('background-color', '#BEBEBE');
                            }
                        },
                        destroy: true,
                        bSort: false
                    });
            },
            error: function (errormessage) {
                alert('error in loading');
                alert(errormessage.responseText);
            }

        })
    };


</script>

<script>
    var complaintShow = function (complaintStatus, OFFICE_CODE, id) {
        var TeamDetailPostBackURL = '/EsclatedComplaints/ShowEsclatedComplaint';
        var officecode = OFFICE_CODE;
        var complaintTypeId = id;
        $.ajax({
            type: "GET",
            url: TeamDetailPostBackURL,
            contentType: "application/json; charset=utf-8",
            data: { "OfficeId": officecode, "complaintStatus": complaintStatus, 'complaintTypeId': complaintTypeId },
            datatype: "json",
            success: function (data) {
                $('#loadRemarkPopUp').html(data);
                $("#EsclatedComplaintPopup").modal('show');
            },
            error: function () {
                alert("Dynamic content load failed.");
            }
        });
    }
</script>

Views/EsclatedComplaints/_EsclatedComplaint.cshtml
@model List<ComplaintTracker.Models.COMPLAINT>

@using (Html.BeginForm("ExportToExcel", "EsclatedComplaints", FormMethod.Get))
{

    <div class="modal fade" id="EsclatedComplaintPopup" tabindex="-1" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header with-border bg-primary text-white">
                    <h2 class="modal-title"> Complaint Details</h2>
                    <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"><span>&times;</span> </button>
                </div>
                <div class="modal-body">
                    <table id="datatables-buttons" class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th>SDO Name</th>
                                <th>Complaint No.</th>
                                <th>Knumber</th>
                                <th>Name</th>
                                <th>Mobile No.</th>
                                <th>Alternate Mobile No.</th>
                                <th>Date</th>
                                <th>Complaint Type</th>
                                <th>complaint source</th>
                                <th>Esclated To</th>
                                <th>Esclated By</th>
                                <th>Esclation Time</th>
                            </tr>
                        </thead>
                        <tbody class="tbody">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.OfficeName</td>
                                    <td>@item.COMPLAINT_NO</td>
                                    <td>@item.KNO</td>
                                    <td>@item.NAME</td>
                                    <td>@item.MOBILE_NO</td>
                                    <td>@item.ALTERNATE_MOBILE_NO</td>

                                    <td>@item.Complaintdate</td>
                                    <td>@item.ComplaintTypeName</td>
                                    <td>@item.ComplaintSource</td>
                                    <td>@item.ASSIGNEEName</td>
                                    <td>@item.Esclated_BY</td>
                                    <td>@item.Esclation_time</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer with-border">
                    @Html.ActionLink("Export to Excel", "ExportToExcel", new { OfficeId = Model[0].excel_OFFICE_CODE, complaintStatus = Model[0].excel_ComplaintStatus, ComplainttypeId = Model[0].excel_ComplainttypeId }, new { @class = "btn btn-primary" })
                     <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">Close</button>
                </div>
            </div>
        </div>
    </div>

}